package com.example.administrator.jiayan_project.db.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.jiayan_project.db.bean.AddressBean;
import com.example.administrator.jiayan_project.db.bean.LikeBean;
import com.example.administrator.jiayan_project.db.bean.KeepPhoneBean;

import com.example.administrator.jiayan_project.db.bean.AddressBeanDao;
import com.example.administrator.jiayan_project.db.bean.LikeBeanDao;
import com.example.administrator.jiayan_project.db.bean.KeepPhoneBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressBeanDaoConfig;
    private final DaoConfig likeBeanDaoConfig;
    private final DaoConfig keepPhoneBeanDaoConfig;

    private final AddressBeanDao addressBeanDao;
    private final LikeBeanDao likeBeanDao;
    private final KeepPhoneBeanDao keepPhoneBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressBeanDaoConfig = daoConfigMap.get(AddressBeanDao.class).clone();
        addressBeanDaoConfig.initIdentityScope(type);

        likeBeanDaoConfig = daoConfigMap.get(LikeBeanDao.class).clone();
        likeBeanDaoConfig.initIdentityScope(type);

        keepPhoneBeanDaoConfig = daoConfigMap.get(KeepPhoneBeanDao.class).clone();
        keepPhoneBeanDaoConfig.initIdentityScope(type);

        addressBeanDao = new AddressBeanDao(addressBeanDaoConfig, this);
        likeBeanDao = new LikeBeanDao(likeBeanDaoConfig, this);
        keepPhoneBeanDao = new KeepPhoneBeanDao(keepPhoneBeanDaoConfig, this);

        registerDao(AddressBean.class, addressBeanDao);
        registerDao(LikeBean.class, likeBeanDao);
        registerDao(KeepPhoneBean.class, keepPhoneBeanDao);
    }
    
    public void clear() {
        addressBeanDaoConfig.clearIdentityScope();
        likeBeanDaoConfig.clearIdentityScope();
        keepPhoneBeanDaoConfig.clearIdentityScope();
    }

    public AddressBeanDao getAddressBeanDao() {
        return addressBeanDao;
    }

    public LikeBeanDao getLikeBeanDao() {
        return likeBeanDao;
    }

    public KeepPhoneBeanDao getKeepPhoneBeanDao() {
        return keepPhoneBeanDao;
    }

}
